version: '3.8'

services:
  products-mcp:
    image: ${ECR_REGISTRY_URL}/${ECR_PRODUCTS_MCP_REPO}:${tag}
    platform: ${platform}
    container_name: products-mcp
    ports:
      - "8000:8000"
    env_file:
      - docker-compose/products-mcp/.env
    environment:
      - JWKS_URI=${JWKS_URI}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    networks:
      - products-network

  products-agent:
    image: ${ECR_REGISTRY_URL}/${ECR_PRODUCTS_AGENT_REPO}:${tag}
    platform: ${platform}
    container_name: products-agent
    ports:
      - "8001:8001"
    env_file:
      - docker-compose/products-agent/.env
    environment:
      - PRODUCTS_MCP_SERVER_URL=http://products-mcp:8000/mcp
    networks:
      - products-network

  products-web:
    image: ${ECR_REGISTRY_URL}/${ECR_PRODUCTS_WEB_REPO}:${tag}
    platform: ${platform}
    container_name: products-web
    ports:
      - "8501:8501"
    env_file:
      - docker-compose/products-web/.env
    environment:
      - PRODUCTS_AGENT_URL=http://products-agent:8001
    networks:
      - products-network

networks:
  products-network:
    external: true
