services:
  products-mcp:
    image: ${ECR_REGISTRY_URL}/${ECR_PRODUCTS_MCP_REPO}:${tag}
    platform: ${platform}
    container_name: products-mcp
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - JWKS_URI=${JWKS_URI}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
