services:
  products-agent:
    image: panchalravi/products-agent:${tag}
    platform: ${platform}
    container_name: products-agent
    ports:
      - "8001:8001"
    volumes:
      - ./.env${target}:/app/.env
